Repository wecode-bootcamp-korea/15-1st-DMFriends-frontend, pull requests merged in 2020-12, with the labels that each got.

#4 [15기 임대호] Add : Footer 작업 완료
  public/data/data.json
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Pages/ProductDetail/ProductDetail.js
  src/Routes.js
  src/config.js
  src/styles/common.scss
Labels: Status: Accepted

#6 [15기 임대호] Fix: 삭제된 초기 세팅 다시 추가
  public/data/data.json
  src/Pages/ProductDetail/ProductDetail.js
  src/Routes.js
  src/config.js
  src/styles/common.scss
Labels: Status: 리뷰 요청

#10 [15기 임대호] Modify : DetailPageHeader 작업 완료
  src/Components/Header/DetailPageHeader/DetailPageHeader.js
  src/Components/Header/DetailPageHeader/DetailPageHeader.scss
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductDetail/ProductDetail.scss
  src/config.js
Labels: Status: Accepted

#1 [15기 김해인] Add : Signup 페이지 코드리뷰 수정 완료 / 기능구현 완료
  public/data/Signup.json
  src/Pages/Login/Login.scss
  src/Pages/Signup/Signup.js
  src/Pages/Signup/Signup.scss
  src/Pages/Signup/components/AgreementForm.js
  src/config.js
  src/styles/common.scss
Labels: Status: 리뷰 요청

#13 [15기 김해인] Add : Login 페이지 UI / 기능구현완료
  public/images/haiinkim/Login.png
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/styles/common.scss
  src/styles/mediaQuery.scss
  src/styles/reset.scss
Labels: Satus: 리뷰 진행 중

#14 [15기 김해인] Signup 페이지 백엔드와 마지막 수정완료
  src/Pages/Signup/Signup.js
  src/Pages/Signup/Signup.scss
  src/styles/common.scss
Labels: Satus: 리뷰 진행 중

#16 [15기 김해인] Add : SideMenu header에 부착 - 피드백 수정완료
  package-lock.json
  public/data/SideMenu.json
  public/images/logoImage/DM_LOGO.png
  src/Components/Header/DetailPageHeader/DetailPageHeader.js
  src/Components/Header/DetailPageHeader/DetailPageHeader.scss
  src/Components/SideMenu/Category/Category.js
  src/Components/SideMenu/Menu/Menu.js
  src/Components/SideMenu/SideMenu.js
  src/Components/SideMenu/SideMenu.scss
  src/Routes.js
  src/config.js
  src/styles/common.scss
  src/styles/reset.scss
Labels: Satus: 리뷰 진행 중

#7 [15기 임태진] Add : NewProducts Page UI/ 리팩토링,컨플릭트해결완료
  package-lock.json
  public/data/NewProducts.json
  public/images/taejinlim/DM_LOGO.png
  public/images/taejinlim/living.jpg
  src/Components/Header/Header.js
  src/Components/Header/Header.scss
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Pages/NewProducts/Components/ItemBox/ItemBox.js
  src/Pages/NewProducts/Components/ItemBox/ItemBox.scss
  src/Pages/NewProducts/Components/NewItemContainer/NewItemContainer.js
  src/Pages/NewProducts/Components/NewItemContainer/NewItemContainer.scss
  src/Pages/NewProducts/Components/SliderBox/SliderBox.js
  src/Pages/NewProducts/Components/SliderBox/SliderBox.scss
  src/Pages/NewProducts/Components/SliderBox/_slick-theme.scss
  src/Pages/NewProducts/Components/SliderContainer/SliderContainer.js
  src/Pages/NewProducts/Components/SliderContainer/SliderContainer.scss
  src/Pages/NewProducts/Components/UpdateItemContainer/UpdateItemContainer.js
  src/Pages/NewProducts/Components/UpdateItemContainer/UpdateItemContainer.scss
  src/Pages/NewProducts/Components/ViewMoreContainer/ViewMoreContainer.js
  src/Pages/NewProducts/Components/ViewMoreContainer/ViewMoreContainer.scss
  src/Pages/NewProducts/NewProducts.js
  src/Pages/NewProducts/NewProducts.scss
  src/config.js
  src/index.js
Labels: Status: 리뷰 요청
